FROM continuumio/miniconda

WORKDIR .
# change working directory to root of nginx webhost
# using WORKDIR is preferred to using 'RUN cd /some/path'

RUN conda install -c conda-forge tensorflow\ 
	&& conda install -c conda-forge blas \
	&& conda install -c anaconda mkl-service \
	&& conda install -c conda-forge/label/cf202003 keras \
	&& conda install -c anaconda pillow

COPY . .

WORKDIR Convolutional_Neural_Networks

# RUN APP
CMD ["python", "my_cnn2.py"]